spring.application.name=Springboot

# DataSource 연결 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/cpsdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=cps
spring.datasource.password=pukimxxx

# MyBatis 매퍼 XML 위치 및 도메인 별칭 설정
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=example.domain